import {
  pf1,
  pf2,
  pf3,
  pf4,
  pf5,
  pf6,
  pf7,
  pf8,
  n1,
  n2,
  n3,
  n4,
  n5,
  n6,
  n7,
  n8,
} from './img'

const Products = [
  {
    id: 1,
    img: pf1,
    pName: 'flowers shirt',
    info: 'made for your style',
    price: 60,
    category: 'T-shirt',
    rate: 4,
  },
  {
    id: 2,
    img: pf2,
    pName: 'flowers shirt',
    info: 'made for your style',
    price: 60,
    category: 'T-shirt',
    rate: 5,
  },
  {
    id: 3,
    img: pf3,
    pName: 'crimson flowers shirt',
    info: 'made for your style',
    price: 60,
    category: 'T-shirt',
    rate: 4.5,
  },
  {
    id: 4,
    img: pf4,
    pName: 'chinese flowers shirt',
    info: 'made for your style',
    price: 60,
    category: 'T-shirt',
    rate: 5,
  },
  {
    id: 5,
    img: pf5,
    pName: 'fluffy flowers shirt',
    info: 'made for your style',
    price: 60,
    category: 'T-shirt',
    rate: 4,
  },
  {
    id: 6,
    img: pf6,
    pName: 'casual shirt',
    info: 'made for your style',
    price: 70,
    category: 'T-shirt',
    rate: 4,
  },
  {
    id: 7,
    img: pf7,
    pName: 'flowers pants',
    info: 'made for your style',
    price: 70,
    category: 'pants',
    rate: 4,
  },
  {
    id: 8,
    img: pf8,
    pName: 'thin shirt',
    info: 'made for your style',
    price: 70,
    category: 'cuts',
    rate: 4,
  },
  {
    id: 9,
    img: n1,
    pName: 'T-shirt gray',
    price: 80,
    info: 'modern and funky',
    category: 'T-shirt',
    rate: 4.5,
  },
  {
    id: 10,
    img: n2,
    pName: 'square T-shirt',
    price: 80,
    category: 'T-shirt',
    rate: 4,
    info: 'squars everywhere',
  },
  {
    id: 11,
    img: n3,
    pName: 'white T-shirt',
    info: 'pure white and clean',
    price: 80,
    rate: 5,
    category: 'T-shirt',
  },
  {
    id: 12,
    img: n4,
    pName: 'army T-shirt',
    info: 'ready to battle',
    price: 75,
    rate: 4,
    category: 'T-shirt',
  },
  {
    id: 13,
    img: n5,
    pName: 'sky blue T-shirt',
    info: 'clear like the sky',
    price: 80,
    rate: 4.5,
    category: 'T-shirt',
  },
  {
    id: 14,
    img: n6,
    pName: 'gray pants',
    info: 'modern look everywhere you go',
    price: 60,
    rate: 4.5,
    category: 'pants',
  },
  {
    id: 15,
    img: n7,
    pName: 'brawn T-shirt',
    info: 'wooden color unique',
    price: 70,
    rate: 4,
    category: 'T-shirt',
  },
  {
    id: 16,
    img: n8,
    pName: 'dark T-shirt',
    info: 'for the peoples love for black',
    price: 80,
    rate: 5,
    category: 'T-shirt',
  },
]
export default Products
